---
title: "Deliverable 1"
author: "Madeline Hoshko"
date: "October 4, 2019"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
library("tidyverse")
library("dplyr")
library("readr")
library("ggplot2")
library("lubridate")
```

```{r}
df <- read.csv('Drug Death Data.csv', na.strings=c("","NA"))
head(df)
df <- select(df, -"ID")
df$Date <- gsub( " .*$", "", df$Date )
df$Date <- as.Date(df$Date, format="%m/%d/%Y")
df$Year <- year(df$Date)


colnames(df)[colnames(df)=="COD"] <- "CauseOfDeath"
colnames(df)[colnames(df)=="DeathCityGeo"]<-"DeathCityCoordinates"
colnames(df)[colnames(df)=="ResidenceCityGeo"]<-"ResidenceCityCoordinates"
colnames(df)[colnames(df)=="InjuryCityGeo"]<-"InjuryCityCoordinates"
df$DeathCityCoordinates <- gsub(".*\\n", "", df$DeathCityCoordinates)
df$ResidenceCityCoordinates <- gsub(".*\\n", "", df$ResidenceCityCoordinates)
df$InjuryCityCoordinates <- gsub(".*\\n", "", df$InjuryCityCoordinates)
df$OtherSignifican <- ifelse(df$OtherSignifican=="Y", "Y", "N")

```
This same substitution to include N for all blank data was used for columns Heroin, Cocaine, Fentanyl, FentanylAnalogue, Oxycodone, Oxymorphone, Ethanol, Hydrocodone, Benzodiazepine, Methadone, Amphet, Tramad, Morphine_NotHeroine, Hydromorphone, Other, AnyOpioid, and OpiateNOS.

```{r, include=FALSE}
df$Heroin <- ifelse(df$Heroin=="Y", "Y", "N")
df$Cocaine <- ifelse(df$Cocaine=="Y", "Y", "N")
df$Fentanyl <- ifelse(df$Fentanyl=="Y", "Y", "N")
df$FentanylAnalogue <- ifelse(df$FentanylAnalogue=="Y", "Y", "N")
df$Oxycodone <- ifelse(df$Oxycodone=="Y", "Y", "N")
df$Oxymorphone <- ifelse(df$Oxymorphone=="Y", "Y", "N")
df$Ethanol <- ifelse(df$Ethanol=="Y", "Y", "N")
df$Hydrocodone <- ifelse(df$Hydrocodone=="Y", "Y", "N")
df$Benzodiazepine <- ifelse(df$Benzodiazepine=="Y", "Y", "N")
df$Methadone <- ifelse(df$Methadone=="Y", "Y", "N")
df$Amphet <- ifelse(df$Amphet=="Y", "Y", "N")
df$Tramad <- ifelse(df$Tramad=="Y", "Y", "N")
df$Morphine_NotHeroin <- ifelse(df$Morphine_NotHeroin=="Y", "Y", "N")
df$Hydromorphone <- ifelse(df$Hydromorphone=="Y", "Y", "N")
df$Other <- ifelse(df$Other=="Y", "Y", "N")
df$AnyOpioid <- ifelse(df$AnyOpioid=="Y", "Y", "N")
df$OpiateNOS <- ifelse(df$OpiateNOS=="Y", "Y", "N")
```


```{r}
head(df)

ggplot(data=df, aes(x=Age)) + 
  geom_histogram(binwidth = 1) + 
  labs(title='Ages of Accidental Drug Related Deaths 2012-2018 in Conneticut', x='Age', y='Number of Deaths')




df$DeathCity <- as.factor(df$DeathCity)
df$DeathCounty <- as.factor(df$DeathCounty)
df$DeathCounty[df$DeathCounty=="USA"] <- NA


filter(df, !is.na(DeathCounty)) %>% 
  ggplot(aes(x=DeathCounty)) +
  geom_bar(stat="count") + 
  labs(title='Number of Accidental Drug Related Deaths 2012-2018 in Conneticut by County', x='county', y='Number of Deaths') + 
  geom_text(stat='count', aes(label=..count..), position=position_dodge(width=0.9), vjust=-0.25)


ggplot(data=df, aes(x=Year, y=..count..))+
  geom_bar() +
  geom_text(stat='count', aes(label=..count..), position=position_dodge(width=0.9), vjust=-0.25)

```

