---
title: "The Opioid Epidemic within the Frame of Connecticut" 
subtitle: "Madeline's Data Science Portfolio" 
output:
  html_document:
    df_print: paged
---

## Abstract

I am very interested in the epidemic that the United States is facing with opioids. I have decided to pursue this subject for my project to gain a better understanding of the problem, as well as view relationships amongst different factors of the epidemic that I am interested in. My dataset is confined to accidental drug deaths within Connecticut and it is my goal to see the relationship Fentanyl has had with overdoses over the years, as well as look into locations of deaths to view whether the proximity to large cities has an impact on the number of deaths. There are many routes to explore and I am planning to find more datasets to increase the options of advancement within this project.

### 1. Discovery and Data Preparation

In my first deliverable, I clean up the data appropriately for ease of use, with column naming, formatting of data and more before using these updated values to create  show death rates over time in terms of gender, location and more. 

Link to my deliverable: [here](./deliverable1.html)
 

### 2. Model Planning and Building

My second deliverable primarily focuses on the addition of new data to create a more complete dataset to visualize, as well as deriving new variables to help aid the creation of predictive models. I begin creating a model to predict the distance of which people overdose compared to where they die as I believe this can be easily correlated to remote areas and safety response delays, as well as more factors displayed within this deliverable. 

Link to my deliverable 2: [here](./deliverable2.html)

### 3. Results and Operationalization

My third deliverable focuses on the constraint of inaccessible data and it's impact on my model. With this restraint, I discuss the next steps needed to operationalize the model as well as the social implications that arise from the actions that this model will heed.

Link to my deliverable 3: [here](./deliverable3.html)
